IMPORTING LIBRARIES

In [19]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

READING AND VIEWING THE DATASET

In [2]:
df = pd.read_csv(r"C:\Users\KIIT\Downloads\heart_disease_data.csv")
df.head(3)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1

CHECK IF THERE EXIST ANY MISSING VALUE IS PRESENT

In [3]:
df.isnull().values.any()

False

In [4]:
df.shape

(303, 14)

1-> INDICATES PATIENT WITH HEART DISEASE
0-> INDICATES PATIENTS WITH NO HEART DISEASE

In [21]:
df['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

In [6]:
X = df.drop(['target'],axis=1)
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [8]:
Y = df['target']
Y.unique()

array([1, 0], dtype=int64)

TRAINING AND TESTING MODEL

In [9]:
x_train,x_test,y_train,y_test = train_test_split(X,Y, test_size= 0.2, random_state= 5)


In [10]:
x_train.shape, y_train.shape

((242, 13), (242,))

TRAINING THE MODEL

In [11]:
log_model = LogisticRegression()
log_model = log_model.fit(x_train,y_train)

c:\Users\KIIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


PREDICTING THE MODEL

In [13]:
log_predict = log_model.predict(x_test)
log_predict

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=int64)

TRAINING MODEL ACCURACY

In [16]:
training_model_accuracy = log_model.score(x_train,y_train)
print(training_model_accuracy)

0.8347107438016529


PREDICTED MODEL ACCURACY

In [24]:
predicted_model_accuracy = log_model.score(x_test,y_test)
print(predicted_model_accuracy)

0.9180327868852459
0.9180327868852459


In [20]:
print(confusion_matrix(y_test,log_predict))

[[27  3]
 [ 2 29]]


TAKING INPUT ON DIFFERENT DATA MODEL TO PREDICT THE PATIENT HEALTH

In [28]:
input_data = (52,1,3,152,298,1,1,178,0,1.2,1,0,3)
input_data_as_numpy = np.asarray(input_data)

input_data_reshaped = input_data_as_numpy.reshape(1,-1)

In [29]:
new_prediction = log_model.predict(input_data_reshaped)
print(new_prediction)

[1]


c:\Users\KIIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
